# Syllabus {.unnumbered}

[{{< bi download >}}]({{< var syllabus-download >}} "Download Syllabus")


::: {.syllabus}

::: {.syllabus-header}

## {{< var subject >}} {.unnumbered}

{{< var institution >}}

{{< var term >}}

[{{< var repo-name >}}]({{< var repo-url >}})

### Professor

{{< var author >}}

{{< var phone >}}

[{{< var email >}}](mailto:{{< var email >}})

Office hours: [[calendly.com/emfink]({{< var appointments >}})]{.mono-font-smaller}

:::

## Description {.unnumbered}

### Overview

The Residency program includes both a field experience and a class component. The class component is an integral part of the work for which you earn academic credit. As your faculty supervisor, I will review your weekly assignments and meet with you periodically as a group and individually to discuss your field experience. I will also communicate with your site supervisor about your progress.

During your residency, you are bound by the professional conduct rules and other standards governing lawyers in your jurisdiction and practice setting. You are expected to resolve any workplace problems with the attorney or others involved. If you cannot resolve the issue yourself, you should discuss it with me. If necessary, we will involve the Residency Program Director. 

### Learning Goals

The Residency course is intended to advance these learning goals:

- Integrate substantive learning with practical experience, assimilate knowledge from the study of law to the practice of law, apply legal doctrines learned in class to a practice setting, and bring knowledge and skills developed in practice back to the classroom;
- Deepen knowledge of the legal profession and lawyers' professional responsibilities and enhance professional development; 
- Increase ability to learn from experience, through feedback from attorneys, self-evaluation, and reflection on practice experience under faculty guidance.

Each student will also identify individual goals and develop a plan for attaining these goals in the residency.

## Policies {.unnumbered}

### Requirements

To receive credit for the Residency, you must complete these course requirements:

- Field placement hours 
- Assigned reading, reports, time logs, and forms (as specified in the Syllabus)
- One hour of professional development
- Individual conferences and group meetings with faculty supervisor
- Midterm conference with site supervisor and faculty supervisor

The following items count toward the required hours (315/7 credits; 360/8 credits): 

 Activity | Hours | Frequency | Total
---|---|--- | ---
Orientation | 8.0 | 1x | 8.0
Group Meetings | 1.5 | 2x | 3.0
Individual Conferences | 0.5 | 2x | 1.5
Preparation of Time Logs & Reports | 1.0 | weekly | 10.0
Wellness Activity | 1.0 | weekly | 10.0
Residency Placement | 28.1 (7 credits); 32.6 (8 credits) | weekly | 281.0 (7 credits); 326.0 (8 credits)

If you complete the requisite number of hours early, you may request to end your field placement one week before the end of the term (but no earlier). Your site supervisor and faculty supervisor must both approve this request. 

[Report prompts](materials/ReportPrompts.pdf), time log, and other required forms and materials are posted on [Moodle](https://moodle.elon.edu/course/view.php?id=79008). Weekly time logs and reports should be submitted on Moodle by 11:59 pm on Sunday (see _Schedule & Assignments_ below). If you encounter problems with Moodle, you may send the assignment to me by email and then submit it to Moodle when you are able.

If you are unable to meet a due date because of your site supervisor's schedule, you should notify me to receive an extension. Extensions will generally not be granted for other reasons absent compelling circumstances.

Unless specifically authorized by the faculty or site supervisor, you may not use generative AI in any work required for this course. Among the many reasons to avoid artificial intelligence,[^1] the most compelling is that it demeans your own intelligence.

[^1]: It is an unreliable tool for legal research, as attorneys continue to learn the hard way. See, e.g., [_Mezu v. Mezu_](https://scholar.google.com/scholar_case?case=3342777015070657049), 2025 WL 3022460 (Md. App. Oct. 29, 2025) (referring attorney to state bar disciplinary authority for filing brief with citations to multiple non-existent cases based on ChatGPT); [_Noland v. Land of the Free, L.P._](https://scholar.google.com/scholar_case?case=6289402711499355924), 114 Cal.App.5th 426 (2025) (upholding sanctions against attorney for filing briefs with numerous fabricated case quotations created by ChatGPT, Claude, Gemini, and Grok); [_Garner v. Kadince_](https://scholar.google.com/scholar_case?case=5585812690204924508), 571 P.3d 812 (Utah App. 2025) (imposing sanctions against attorney for filing brief with citations to non-existent cases created by ChatGPT). It consumes "a staggering amount of electricity" and water, imposing significant social and environmental costs. Adam Zewe, [Generative AI’s environmental impact](https://news.mit.edu/2025/explained-generative-ai-environmental-impact-0117), MIT News (Jan. 17, 2025); UN Environment Program, [AI has an environmental problem. Here’s what the world can do about that](https://www.unep.org/news-and-stories/story/ai-has-environmental-problem-heres-what-world-can-do-about) (Nov. 13, 2025). It makes you stupid. Nataliya Kosmyna, et al, [Your Brain on ChatGPT: Accumulation of Cognitive Debt when Using an AI Assistant for Essay Writing Task](https://www.media.mit.edu/publications/your-brain-on-chatgpt/), MIT Media Lab (2025). 

### Grading 

The course will be graded on a pass/fail basis, based on these standards: 

- Completion of required field placement hours;
- Attendance & participation in group meetings and individual conferences;
- Timely submission of all forms, reports, and time logs; and 
- Professionalism in dealing with your field supervisor, faculty supervisor, clients, and others during the residency.

Exemplary performance in your field placement, assignments, and group meetings may earn a High Pass. Failure to meet these standards may result in a Low Pass or a failing grade.

### Disability Accommodations

For disability accommodation requests, contact the [Elon Academic Accommodations Office](https://www.elon.edu/u/law/students/student-resources/academic-accommodations-accessibility/).

### Honor Code

The Law School [honor code](https://www.elon.edu/e/law/student-experience/honor-code.html) applies to all activities related to your law school study, including conduct during class and examinations. 

## Schedule & Assignments {.unnumbered}

### Orientation (January 5)

#### Assignments

- [NC Rules of Professional Conduct](https://www.emfink.net/Residency/materials/NCRPC.pdf)
- Neil Hamilton, [_Roadmap_](https://www.emfink.net/Residency/materials/HamiltonRoadmap.pdf)
- [ABA Standards 302-303](https://www.emfink.net/Residency/materials/ABAstandards.pdf)
- Jacob Doe v. University of North Carolina System, 1:23-cv-00041 [(Order to Show Cause)](https://www.emfink.net/Residency/materials/DoeUNC-Order-10Nov2025.pdf) (W.D.N.C. Nov. 10, 2025)
- [Leadership Skills for Attorney Success](https://www.emfink.net/Residency/materials/LeadershipSkillsForAttorneySuccess.pdf)
- Initial Self-Evaluation of Lawyering Skills (_Available on [Moodle](https://moodle.elon.edu/course/view.php?id=79148)_)

#### Practice Group Meeting

3:00 pm, Room 211

### Week 1 (January 5-11)

#### Assignments 

- Week 1 Report (Wellness)
- Memorandum of Understanding
- Confidentiality Agreement
- Draft Goal Statement
- Time Log

### Week 2 (January 12-18)

#### Assignments 

- Week 2 Report (Audio Recording)
- Time Log
- Final Goal Statement
- Schedule individual conference with faculty supervisor for Week 3 ([calendly.com/emfink/](https://calendly.com/emfink/))

### Week 3 (January 19-25)

#### Meeting 

Individual conference with faculty supervisor (as previously scheduled) by telephone or Zoom

#### Assignments 

- Week 3 Report (Organizational Structure)
- Time Log

### Week 4 (January 26-February 1)

#### Assignments  

- Week 4 Report (Supervision and Feedback)
- Time Log

### Week 5 (February 2-8)

#### Meeting 

Practice group meeting (date & time TBA)

#### Assignments 

- Week 5 Report (Residency Experience)
- Time Log
- Midterm Self-Evaluation of Lawyering Skills
- Site Supervisor's Midterm Evaluation
- Schedule conference with site supervisor and faculty supervisor for Week 6 ([calendly.com/emfink/](https://calendly.com/emfink/))

### Week 6 (February 9-15)

#### Meeting 

Conference with site supervisor and faculty supervisor (date and time as scheduled), by telephone or Zoom

#### Assignments 

- Week 6 Report (Project Analysis)
- Time Log    

### Week 7 (February 16-22)

#### Assignments  

- Week 7 Report (Cultural Competence & Leadership)
- Time Log
- Professional development activity (CLE program or other activity approved by faculty supervisor). See the NC Bar Association website ([ncbar.org](https://ncbar.org)) for CLE options.
- Schedule individual conference with faculty supervisor for Week 8 ([calendly.com/emfink/](https://calendly.com/emfink/))
  
### Week 8 (February 23-March 1)

#### Meeting 

Individual conference with faculty supervisor (as scheduled above) by telephone or Zoom

#### Assignments 

- Week 8 Report (Projects and Assignments)
- Time Log
      
### Week 9 (March 2-8)

#### Meeting 

Practice group meeting (date and time TBA) by Zoom ([elon.zoom.us/my/emfink](https://elon.zoom.us/my/emfink))

#### Assignments 

- Week 9 Report (Learning Milestones)
- Time Log
- Site Supervisor's Final Evaluation

### Week 10 (March 9-15)

#### Assignments 

- Week 10 Report (Residency Summary)
- Time Log
- Student Evaluation of Placement
- Final Self-Evaluation of Lawyering Skills
- Site Supervisor's Final Evaluation
- Certificate of Completion
- Thank you note to site supervisor

:::