---
title: Residency
subtitle: Weekly Reports
author: Eric M. Fink
affiliation: Elon University School of Law
date: 'Winter 2026'

format:
  pdf:
    template: default_emf.tex
    output-file: WeeklyReports

---

## General Guidelines

Use this format for all written reports: 

- Heading: 
	- Name
	- Week Number
	- Title
- Content: 
	- Response to prompt
- Length: 
	- 2-4 pages (double-spaced)

## Week 1

### Wellness Plan

Each week during the Residency, you will devote one hour to a wellness activity of your choosing. Identify your wellness goals and create a plan for weekly activities to meet those goals. 

You should include one-hour for your wellness activity in your time log each week, with a brief description and reflection. 

### Learning Goals and Plan

Identify your learning goals (4-6) for the Residency and your plans for meeting them (using the template on Moodle). Post your draft Learning Goals and Plan on Moodle. After review the draft with your Site Supervisor and incorporating any suggestions or revisions, post your final Learning Goals and Plans on Moodle. 


_Examples of Goals: _

1. Enhance knowledge of law in area of placement;
2. Improve research and writing; 
3. Develop legal practice skills (e.g. client interviewing, case management, oral advocacy, etc.)

## Week 2 

### Reflection on work assignment

Prepare and record (using the audio recording feature in Moodle) a brief (2-4 minutes) statement describing an assignment listed in your time log and what you learned from it. Use this exercise as a guide for describing your work in future time log entries. 

## Week 3 

### Organizational Structure & Practice

Describe the work and organization of your residency placement. This may include the following points, as relevant to your placement setting: 

* Type of organization
* Area of law
* Types of clients 
* Conflict screening and management
* Job duties of attorneys
* How work is assigned and supervised

## Week 4 

### Supervision and Feedback

Choose an assignment you have completed and describe the supervision and feedback you received, e.g. 

* Who gave you the assignment and what instructions did they give ?
* What you did to ensure you understood the assignment?
* How did you approached and complete the assignment? e.g. where did you start; what interim guidance/feedback did you seek/receive before completing the assignment; what tools or resources did you use for research; etc. 
* What feedback did you receive after completing the assignment?
* What did you learn from this assignment?

## Week 5 

### Mid-Term Reflection on Residency

Assess your experience so far, e.g. 

* What have you done? 
* What have you learned?
* Are you meeting your goals for the Residency? Have your goals changed? 
* How have your interactions been with your Site Supervisor and other attorneys/staff? 

## Week 6  

### Project and Billing Analysis

Prepare a summary of your work on one project/assignment: 

1. From your time log entries, prepare an itemized list of the tasks you’ve completed, and time spent on each task for the project/assignment. 
2. From your responses to the previous weekly reports, add your reflections on your work for the project/assignment.
3. Assess your work on the project/assignment and the time you spent on the various tasks and indicate what you learned.

## Week 7 

### Professional Development, Cultural Competence, & Leadership

Prepare and submit a report on each of the following:

#### 1. Professional Development 
   
Attend one hour of professional development of your choice (either a free CLE through the NC Bar Association or a program you participated in at your residency placement). Describe the program and what you learned.
Note: You may complete this assignment at any time during the term. 


#### 2. Cultural Competence

Review ABA Standards 302-303 (see Syllabus: Orientation Assignments). 
Explain what “cultural competence” means to you and its relevance for your professional identity and career goals. 


#### 3. Leadership

Review  the reading on “Leadership Skills for Attorney Success” (see Syllabus: Orientation Assignments). 

Explain what “leadership in the legal profession” means to you, describe the attributes you associate with “leadership”, and give an example of someone you regard as an example of “leadership in the legal profession”. 

## Week 8 

### List of Assignments and Projects

Create an itemized list (organized by assignment/project type, not chronologically) of the projects on which you have worked, indicating the number of assignments you have completed for each item. 

_Examples:_

* Drafted pleadings, motions, and discovery requests: 
   * Complaints (4)
   * Answers (2)
   * Pre-trial motions (1)
   * Discovery requests (3)
* Court or Other Proceedings (indicate whether you observed or participated)
   * Arraignments (2)
   * Trial (4 days)
   * Sentencing hearings (2)
* Client interactions
   * Intake meetings (3)
   * Deposition prep (2)

Update and complete this list at the end of the Residency. 

_**Do not include any confidential information.**_

## Week 9: 

### Learning Milestones

Summarize what you have learned in the Residency in relation to your learning goals and career plans. E.g. What challenges did you encounter and how did you respond? What did you find most rewarding? Are there any goals you did not meet? Did you find the wellness activity beneficial? 

## Week 10 

### Overview of Residency

Summarize your Residency experience, covering these points: 

* Residency placement: organizational mission and structure; areas of law; types of legal work, etc. 
* What you did: types of work, areas of law, etc. 
* What you learned: knowledge & skills; challenges; etc. 

For this report, you may use any format or medium that you choose (e.g. textual document, slide or other visual presentation, interpretive dance, musical ballad, epic poem, etc.).